# Generated by Django 3.0.8 on 2020-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autherregistration',
            name='conformpassword',
            field=models.CharField(default='diapk', max_length=150),
        ),
    ]
