# Generated by Django 3.0.8 on 2020-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_autherregistration_conformpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autherregistration',
            name='conformpassword',
            field=models.CharField(max_length=150),
        ),
    ]
