# Generated by Django 3.0.8 on 2020-07-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200719_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autherregistration',
            name='conformpassword',
        ),
    ]
